services:
  dubble-postgres:
    image: postgres
    restart: always
    container_name: db-dubble
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dubble
      POSTGRES_DB: dubble
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
