name = "webhooks"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Default environment variables
[vars]
NODE_ENV = "production"

# Development environment variables
[env.development]
vars = { NODE_ENV = "development" }

# Production environment variables
[env.production]
vars = { NODE_ENV = "production" }

[dev]
port = 8787
