name = "webhooks"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[build]
command = "bun install && bun esbuild.config.js"