name: run-migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: migrate
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_ONLY: true

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: |
          cd packages/database
          bun install
          cd ../..
      - run: bun gen
      - run: bun migrate
