name: run-migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: migrate
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_ONLY: true

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
      - run: npm config set "//registry.tiptap.dev/:_authToken" ${{ secrets.TIPTAP_AUTH_TOKEN }}
      - run: bun install
      - run: bun gen
      - run: bun migrate
